# Generated by Django 4.2 on 2024-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
